import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import {getServerSession} from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from './LogoutBtn'
import { cookies } from 'next/dist/client/components/headers'
import DarkMode from './darkmode'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  let cookie = cookies().get('mode')
  
  return (
    <html lang="en">
      <body style={{background: 'white'}} className={
      cookie != undefined && cookie.value == 'dark' 
        ? 'dark-mode'
        : ''}>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          <Link href="/write">글쓰기</Link> 
          <Link href="/register">회원가입</Link> 
          <DarkMode/>
          {
            session 
            ? <div style={{display: 'flex', position: 'absolute' ,right: '20px', top: '20px'}}>
                <span style={{borderBottom: '2px solid blue', padding: '5px', marginRight: '10px'}}>
                  {session.user.name}
                </span> 
                <LogoutBtn/> 
              </div> 
            : <div style={{display: 'flex', position: 'absolute' ,right: '20px', top: '20px'}}>
                <LoginBtn/>
              </div>
          }
        </div>  
      <hr/>
        {children}
        </body>
    </html>
  )
}
